### ISSUE TITLE
Codecov integration is broken

### ISSUE THREAD

**Issue by 304NotModified** [YAXLib/YAXLib#114]
Probable can't handle the rename/move of the repo

**Comment by 304NotModified** [comment]
Very strange, calculating the coverage worked in my project https://ci.appveyor.com/project/NuGetPackageExplorer/yaxlib

But not in the current project

**Comment by 304NotModified** [comment]
Seems to be broken after https://github.com/YAXLib/YAXLib/pull/108

**Comment by axunonb** [comment]
Running the following test script manually in AppVeyor made it work:
```
cd %APPVEYOR_BUILD_FOLDER%\YAXLibTests
nuget install Appveyor.TestLogger
dotnet add package AltCover
cd ..
dotnet test --framework net5.0 --test-adapter-path:. --logger:Appveyor YAXLibTests /p:AltCoverXmlReport="..\coverage.xml" /p:AltCover=true /p:AltCoverStrongNameKey="%APPVEYOR_BUILD_FOLDER%\Key\YAXLib.DevKey.snk" /p:AltCoverAssemblyExcludeFilter="YAXLibTests|NUnit3.TestAdapter" /p:AltCoverLineCover="true"
nuget.exe install -Version 1.11.2 codecov
%APPVEYOR_BUILD_FOLDER%\Codecov.1.11.2\Tools\win7-x86\codecov.exe -f "%APPVEYOR_BUILD_FOLDER%\YAXLibTests\coverage.net5.0.xml"
```
If I remember right, I had the same issue in another repo and the reason were the path names in `coverage.xml`
appveyor.yml is not changed yet.
@304NotModified What do you think?

**Comment by axunonb** [comment]
Does #115 already fix this issue, and should we merge the PR? Was not sure about the remark "don't merge yet".

**Comment by 304NotModified** [comment]
No it doesn't? You could of course see it in the logs ;)

**Comment by 304NotModified** [comment]
@axunonb  thanks for fixing this. But this wasn't a PR? It's a bit hard to track when this is fixed. 

CodeCov looks strange, dunno if this is fixed

https://app.codecov.io/gh/YAXLib/YAXLib/branch/master

![image](https://user-images.githubusercontent.com/5808377/111383652-cbfe4b00-86a8-11eb-92f8-947036a504de.png)

**Comment by axunonb** [comment]
I saw that. The fix is one thing, and existing data on Codecov is another. After the fix, the correct coverage is submitted.
There are 2 commits ([15 Feb](https://codecov.io/gh/YAXLib/YAXLib/commit/31fec26e66a4f6c13784198089bfadd2c380a3d1/) and [18 Feb](https://codecov.io/gh/YAXLib/YAXLib/commit/a89adf730153d5994c96d3ea1e0718d50de5224a/)) that "break" the graph. The last commit before goes back to 09 Aug 2017.
The years 2017-2020 with no commits don't bring too much value. Would it make sense to start fresh and [erase content on codecov](https://app.codecov.io/gh/YAXLib/YAXLib/settings)? I see no way to getting rid of the disturbing data.
