### ISSUE TITLE
String fields formating

### ISSUE THREAD

**Issue by leandro-almeida** [YAXLib/YAXLib#156]
**Is your feature request related to a problem? Please describe.**
No, but it would avoid programming errors/problems from the developer consuming this lib.

**Describe the solution you'd like**
Would be great if we could do something like this:

```csharp
[YAXStringToUpper()]
[YAXStringToLower()]
[YAXStringMaxLength(40)]
```

**Describe alternatives you've considered**
* I think i could write a custom serializer, but i dont know how to pass parameters to it, like max 40 chars.
* Other option is creating a builder class to build my mapped yax class, and when settings the string values do the desired operations on strings.

**Comment by leandro-almeida** [comment]
Forgot to mention that YAXLib is awesome, simple to use and simply works! Thanks!

**Comment by axunonb** [comment]
Hi and thanks for your feedback!

> Would be great if we could do something like this

No sure whether attributes would be the right way to cover the virtually endless requirements for formatting generically.

> I think i could write a custom serializer, but i dont know how to pass parameters to it, like max 40 chars.

YAXLib will pass a reference of the object to serialize to your custom serializer. You could decorate your class properties with additional ("not YAXLib") attributes in order to pass parameters to the custom serializer. Would this help for your use case?
If you haven't yet, please take a look at these [examples how to implement a custom serializer](https://github.com/YAXLib/YAXLib/blob/master/YAXLibTests/CustomSerializerTests.cs).

**Comment by leandro-almeida** [comment]
Thanks for replying, i'll try with custom serializers.
