### ISSUE TITLE
Define a ReSharper profile for an agreed code style

### ISSUE THREAD

**Issue by asbjornu** [YAXLib/YAXLib#17]
The solution should provide a ReSharper `.DotSettings` file that will provide a coherent set of naming conventions and cleanup rules for the source code in YAXLib.

**Comment by axunonb** [comment]
Recently we introduced `.editorconfig`, which is the standard for declaring common basic settings that can be picked up by many editors and IDE's. So partly this issue is already covered.

DotSettings is a file that ReSharper uses to save "team shared" settings. Shouldn't be too difficult to agree on. Still we cannot rely on contributors having ReSharper in use.
@NKnusperer @304NotModified Close and leave as it is, or introduce DotSettings?

**Comment by NKnusperer** [comment]
Personally I use JetBrains Rider which supports `.DotSettings` so this is fine, however `.editorconfig` is platform agnostic so it covers a broader audience. It might be good idea to use it.
