### ISSUE TITLE
Problem on deserialization

### ISSUE THREAD

**Issue by Hunv** [YAXLib/YAXLib#92]
Hi,

I have the attached Class(es). I also have a XML string I like to deserialize. It fails with error "YAXLib.YAXElementMissingException: No elements with this name found: './Item'." but there is a property calles "Item" in the class.

The code I am using:
```
var xml2 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?> <Trias xmlns=\"http://www.vdv.de/trias\" version=\"1.2\"> <ServiceDelivery> <ResponseTimestamp xmlns=\"http://www.siri.org.uk/siri\">2018-04-22T15:40:20Z</ResponseTimestamp> <ProducerRef xmlns=\"http://www.siri.org.uk/siri\">EFAController10.2.10.2-EFA-STATIC02</ProducerRef> <Status xmlns=\"http://www.siri.org.uk/siri\">true</Status> <MoreData>false</MoreData> <Language>de</Language> <DeliveryPayload> <LocationInformationResponse> <LocationResult> <Location> <StopPoint> <StopPointRef>de:08115:5947</StopPointRef> <StopPointName> <Text>Hauptstraße</Text> <Language>de</Language> </StopPointName> <LocalityRef>8115051:6</LocalityRef> <WheelchairAccessible>false</WheelchairAccessible> <Lighting>false</Lighting> <Covered>false</Covered> </StopPoint> <LocationName> <Text>Weil im Schönbuch</Text> <Language>de</Language> </LocationName> <GeoPosition> <Longitude>9.05147</Longitude> <Latitude>48.62194</Latitude> </GeoPosition> </Location> <Complete>true</Complete> <Probability>0.958000004</Probability> <Mode> <PtMode>bus</PtMode> <BusSubmode>localBus</BusSubmode> </Mode> <Mode> <PtMode>bus</PtMode> <BusSubmode>expressBus</BusSubmode> </Mode> <Mode> <PtMode>bus</PtMode> <BusSubmode>demandAndResponseBus</BusSubmode> </Mode> </LocationResult> </LocationInformationResponse> </DeliveryPayload> </ServiceDelivery> </Trias>";

var ser = new YAXLib.YAXSerializer(typeof(Trias));
var res2 = ser.Deserialize(xml2);
```

Is it my fault or is something else wrong?
Here is the class I am talking about:
[Trias.zip](https://github.com/sinairv/YAXLib/files/1963722/Trias.zip)

This class is based on this xsd files:
https://www.vdv.de/trias-xsd-v1.2.zipx?forced=true

**Comment by Hunv** [comment]
Hi, yes I used xsd2code. What do I need to change? I don't understand what I am doing wrong.

**Comment by justeff** [comment]
Why not stick with XmlSerializer? Or with DataContract Serializer? If you want to use YAXlib you are forced to manually edit the generated classes you get from xsd2code. I planned to fork YAXLib and make them compatible with the XmlSerializer tags like XmlElement, XmlAttribute, but I discovered a serious drawback. Atm, it can't resolve the class type through the tag names, it needes a xsi:type.

The main page should help you with the needed transformation (XmlAttribute -> YAXAttributeForClass and if needed YAXSerializeAs, XmlElement -> YAXSerializeAs (if another xml name is needed, otherwise you need no special tag and you can delete XmlElement  fully).

**Comment by axunonb** [comment]
@Hunv: It's been a while ago, but did @justeff 's answer help, so this issue could be closed?

**Comment by Hunv** [comment]
You can close, but I don't know if it helped or not ;)
